/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sybila_parasim_computation_simulation_lsoda_LsodaWrapper */

#ifndef _Included_org_sybila_parasim_computation_simulation_lsoda_LsodaWrapper
#define _Included_org_sybila_parasim_computation_simulation_lsoda_LsodaWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sybila_parasim_computation_simulation_lsoda_LsodaWrapper
 * Method:    wrappedFunc
 * Signature: ([[B[[F[[I[FFFJF[F)[F
 */
JNIEXPORT jobject JNICALL Java_org_sybila_parasim_computation_simulation_lsoda_LsodaWrapper_wrappedFunc
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jfloatArray, jfloat, jfloat, jlong, jfloat, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
