name: Docker Build and Publish Image
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: sybila/parasim
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Prepare
      id: prepare
      run: |
        echo ::set-output name=docker_image::${DOCKER_IMAGE}
        echo ::set-output name=release_tag::${{ github.event.release.tag_name }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: |
        docker build \
        --tag ${{ steps.prepare.outputs.docker_image }}:latest \
        --tag ${{ steps.prepare.outputs.docker_image }}:${{ github.event.release.tag_name }} \
        .
    - name: Publish Docker image
      # Only deploy if using master on original repo (and not for pull requests or forks)
      if: github.repository_owner == 'sybila' && github.ref == 'refs/heads/master'
      run: |
        docker push --all-tags ${{ steps.prepare.outputs.docker_image }}
